"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ArrowLeft, Heart, MessageCircle, Share, MoreHorizontal, Plus } from "lucide-react"
import Link from "next/link"

export default function CommunityPage() {
  const communityPosts = [
    {
      id: 1,
      user: "Priya Sharma",
      location: "Chennai, Tamil Nadu",
      time: "2 hours ago",
      content:
        "Just completed this beautiful Diwali Kolam! Took me 3 hours but totally worth it. The AI scanner helped me perfect the symmetry. 🪔✨",
      image: "/beautiful-diwali-kolam-with-diyas.png",
      likes: 127,
      comments: 23,
      shares: 8,
      tags: ["Diwali", "Traditional", "Chennai"],
    },
    {
      id: 2,
      user: "Lakshmi Reddy",
      location: "Hyderabad, Telangana",
      time: "5 hours ago",
      content:
        "My grandmother's 80th birthday Muggulu design! She taught me this pattern 20 years ago. Using Kolam Studio to preserve it forever 💕",
      image: "/traditional-grandmother-muggulu-pattern-telugu.png",
      likes: 89,
      comments: 31,
      shares: 12,
      tags: ["Family", "Heritage", "Muggulu"],
    },
    {
      id: 3,
      user: "Kavitha Nair",
      location: "Kochi, Kerala",
      time: "1 day ago",
      content:
        "Onam special Pookalam design generated by AI! The colors came out so vibrant. Can't wait to try this with real flowers tomorrow 🌺🌸",
      image: "/colorful-onam-pookalam-flower-rangoli-kerala.png",
      likes: 156,
      comments: 18,
      shares: 25,
      tags: ["Onam", "Pookalam", "AI Generated"],
    },
    {
      id: 4,
      user: "Meera Rao",
      location: "Bangalore, Karnataka",
      time: "2 days ago",
      content:
        "Morning Rangoli practice session! The AI suggestions helped me improve my dot placement. Consistency is key! 🎯",
      image: "/morning-rangoli-practice-dots-symmetrical.png",
      likes: 73,
      comments: 15,
      shares: 6,
      tags: ["Practice", "Morning", "Rangoli"],
    },
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-red-50 to-purple-50">
      {/* Header */}
      <header className="fixed top-0 w-full z-50 glass border-b border-primary/20">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <Link href="/" className="flex items-center gap-3">
              <ArrowLeft className="w-5 h-5" />
              <div className="text-2xl">🎨</div>
              <div>
                <h1 className="text-xl font-bold text-foreground">Kolam Studio</h1>
                <p className="text-xs text-muted-foreground">Community</p>
              </div>
            </Link>
            <Button className="bg-primary hover:bg-primary/90">
              <Plus className="w-4 h-4 mr-2" />
              Share Design
            </Button>
          </div>
        </div>
      </header>

      <div className="pt-32 pb-20 px-4">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <h1 className="text-4xl md:text-5xl font-bold mb-6 animate-gradient bg-gradient-to-r from-[color:var(--color-tamil-orange)] via-accent to-purple-600 bg-clip-text text-transparent">
              Community
            </h1>
            <p className="text-xl text-foreground/80 mb-8 max-w-2xl mx-auto leading-relaxed text-balance">
              Share your Kolam creations and connect with artists across South India
            </p>
          </div>

          {/* Community Stats */}
          <div className="grid grid-cols-3 gap-4 mb-8">
            <Card className="glass-card text-center">
              <CardContent className="p-4">
                <div className="text-2xl font-bold text-foreground">2.5K</div>
                <div className="text-sm text-muted-foreground">Active Artists</div>
              </CardContent>
            </Card>
            <Card className="glass-card text-center">
              <CardContent className="p-4">
                <div className="text-2xl font-bold text-[color:var(--color-tamil-orange)]">8.9K</div>
                <div className="text-sm text-muted-foreground">Designs Shared</div>
              </CardContent>
            </Card>
            <Card className="glass-card text-center">
              <CardContent className="p-4">
                <div className="text-2xl font-bold text-[color:var(--color-telugu-blue)]">15K</div>
                <div className="text-sm text-muted-foreground">Likes Given</div>
              </CardContent>
            </Card>
          </div>

          {/* Community Posts */}
          <div className="space-y-6">
            {communityPosts.map((post) => (
              <Card key={post.id} className="glass-card">
                <CardHeader>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 bg-gradient-to-r from-primary to-accent rounded-full flex items-center justify-center text-white font-semibold">
                        {post.user
                          .split(" ")
                          .map((n) => n[0])
                          .join("")}
                      </div>
                      <div>
                        <h3 className="font-semibold text-foreground">{post.user}</h3>
                        <p className="text-sm text-muted-foreground">
                          {post.location} • {post.time}
                        </p>
                      </div>
                    </div>
                    <Button variant="ghost" size="sm">
                      <MoreHorizontal className="w-4 h-4" />
                    </Button>
                  </div>
                </CardHeader>
                <CardContent className="space-y-4">
                  <p className="text-foreground leading-relaxed">{post.content}</p>

                  <div className="rounded-lg overflow-hidden">
                    <img
                      src={post.image || "/placeholder.svg"}
                      alt="Community post"
                      className="w-full h-64 object-cover"
                    />
                  </div>

                  <div className="flex flex-wrap gap-2">
                    {post.tags.map((tag) => (
                      <Badge key={tag} variant="outline" className="text-xs">
                        #{tag}
                      </Badge>
                    ))}
                  </div>

                  <div className="flex items-center justify-between pt-4 border-t border-border/50">
                    <div className="flex items-center gap-6">
                      <Button
                        variant="ghost"
                        size="sm"
                        className="flex items-center gap-2 text-muted-foreground hover:text-red-500"
                      >
                        <Heart className="w-4 h-4" />
                        {post.likes}
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="flex items-center gap-2 text-muted-foreground hover:text-blue-500"
                      >
                        <MessageCircle className="w-4 h-4" />
                        {post.comments}
                      </Button>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="flex items-center gap-2 text-muted-foreground hover:text-green-500"
                      >
                        <Share className="w-4 h-4" />
                        {post.shares}
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* Load More */}
          <div className="text-center mt-8">
            <Button variant="outline" size="lg">
              Load More Posts
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
